name: Deploy Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/jekyll-build-pages@v1.0.13
    # - uses: actions/checkout@v4
    # - name: Build the site in the jekyll/builder container
    #   run: |
    #     docker run \
    #     -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
    #     jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    #                 - name: Build Jekyll for GitHub Pages
